name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build release
        run: make release

      - name: Generate release notes
        id: release_notes
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --latest --strip header

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .build/release-app/Parrot-*-macos-arm64.dmg
          body: ${{ steps.release_notes.outputs.content }}
